version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/golang/Dockerfile
    ports:
      - "8081:8080"
    command:
      "/bin/coach"
  db:
    image: mongo
    restart: always
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: coach
      MONGO_INITDB_ROOT_USERNAME: coach
      MONGO_INITDB_ROOT_PASSWORD: 123456
